version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      SA_PASSWORD: "YourStrongPassw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"