version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      SA_PASSWORD: "YourStrongPassw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
  app:
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "YourStrongPassw0rd"
      ACCEPT_EULA: "Y"
    links:
      - 'db:1401'      
